baseURL = "https://example.org"
languageCode = "en-us"
title = "terminal-cookbook"
theme = "terminal-cookbook"

# optional, if you want to use plain html
# in your markdown recipe files
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
